#!/usr/bin/env python
import rospy
from gazebo_utils.gazebo_world_to_map import MapCreator


if __name__ == '__main__':
    rospy.init_node("map2odom_transform_publisher")
    map = MapCreator()
    map.runMapOdomPublisher()

    rospy.spin()

